### ISSUE TITLE
[UPDATE] customer endpoint outdated! or does not work

### ISSUE THREAD

**Issue by steinathan** [stitchng/paystack#15]
The API endpoint attribute at [https://github.com/stitchng/paystack/blob/788b7e7d9b8238e940609456f22276ac3f9db433/src/endpoints/customers.js#L46](https://github.com/stitchng/paystack/blob/788b7e7d9b8238e940609456f22276ac3f9db433/src/endpoints/customers.js#L46) should be changed to  ` path: '/customer/{:id_or_customer_code}` [https://developers.paystack.co/reference#update-customer](https://developers.paystack.co/reference#update-customer)  the above query doest scale well or throws an error
```js
 Request endpoint does not exist | Not Found (404)
    at PayStack.httpClientBaseOptions.hooks.afterResponse (/home/.../.../node_modules/paystack-node/src/PayStack/index.js:330:21)
    at EventEmitter.<anonymous> (/home/.../.../node_modules/paystack-node/node_modules/got/source/as-promise.js:39:23)
```
This should be updated to also support `customer_id`

**Comment by isocroft** [comment]
Thanks so much @navicstein  for bringing this up. Will use this opportunity to comb through the API documentation for any other updates

**Comment by stitchng** [comment]
@isocroft thanks for the fix. New version out now on NPM v0.2.4

**Comment by steinathan** [comment]
Thanks for upgrading the module, i appreciate
