### ISSUE TITLE
[Improve error reporting] Request was badly formed | Bad Request (400)

### ISSUE THREAD

**Issue by steinathan** [stitchng/paystack#16]
When testing  `paystack.initiateTransfer({... .. })` the server always returns with 400 no matter what i do, below is the argument i passed into the function

```js
{
  reason: 'Withdrawing from ***: United Bank For Africa',
  amount: 40000,
  recipient: 'RCP_gqko5hey45189ob',
  reference: 'rApY3'
}
```

I don't really know what am doing wrong here, but using the `curl` method just works fine, the recipient is from an already generated endpoint and am just passing it directly to the `initiateTransfer` method

this is the specification am following [https://developers.paystack.co/v2.0/docs/funds-transfers](https://developers.paystack.co/v2.0/docs/funds-transfers)

[EDIT]
Ive also disabled OPT confirmation, but still no positive reply from paystack

**Comment by isocroft** [comment]
Hello @navicstein , I have checked and rechecked the flow from the specification [link](https://developers.paystack.co/v2.0/docs/funds-transfers) you pasted above and also the API docs for **[initiateTransfer](https://developers.paystack.co/reference#initiate-transfer)** and I believe you are doing something wrong. I will like to have more context on the issue e.g. _screenshots of the NodeJS app console logs_, _code snippet in your NodeJS app utilizing the [**funds transfer**](https://developers.paystack.co/v2.0/docs/funds-transfers) flow_ to be able to help properly.

Also check if your test/live API key is available in your app and is also correct.

However, error reporting will be greatly improved in the new release **v0.2.5**

**Comment by steinathan** [comment]
@isocroft i finally resolved the problem, the problem was that i was passing a wrong reference code that contained bad characters and i did'nt have enough money in my paystack account, this issues should be closed as ive resolved it, but thanks for the support
