### ISSUE TITLE
the correct format of paystack.chargeCard()

### ISSUE THREAD

**Issue by Tetranyble** [stitchng/paystack#17]
I have been experiencing error in the chargeCard function with the following object as a parameter to the chargeCard function:
```
{
  "email":"some@body.nice",
  "amount":"10000",
  "metadata":{
    "custom_fields":[
      {
        "value":"makurdi",
        "display_name": "Donation for",
        "variable_name": "donation_for"
      }
    ]
  },
  "card":{
    "cvv":"408",
    "number":"4084084084084081",
    "expiry_month":"01",
    "expiry_year":"99"
  },
  "pin":"0000"
}
```
[Source: ](https://documenter.getpostman.com/view/2770716/paystack-api/7187aMn?version=latest#32aa812e-e319-b0e2-114d-fefc5a7be6e7)
and here is the errror i get:
```
Error: Request was badly formed | Bad Request (400)
    at PayStack.httpClientBaseOptions.hooks.afterResponse (C:\xampp\htdocs\blake\node_modules\paystack-node\src\PayStack\index.js:331:21)
    at EventEmitter.<anonymous> (C:\xampp\htdocs\blake\node_modules\got\source\as-promise.js:39:23)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```
and just to dig up thing i had to go into that file and console log at line 309 and here's what i got even after changing the card details to a real card:
```
body: '{\n  "status": false,\n  "message": "Please pass card number to charge"\n}'
```

**Comment by stitchng** [comment]
@Tetranyble Thanks for raising this issue. We will have someone look into it soon. However, i think this is an issue with the *PayStack API* itself

**Comment by Tetranyble** [comment]
please do. we're at stand still in our project

**Comment by Tetranyble** [comment]
> @Tetranyble Thanks for raising this issue. We will have someone look into it soon. However, i think this is an issue with the _PayStack API_ itself

so how can this be resolved at the moment?

**Comment by devamaz** [comment]
@Tetranyble Thanks for the feedback this is currently being resolved

**Comment by Tetranyble** [comment]
This is taking too long to resolve

**Comment by stitchng** [comment]
@Tetranyble , please find the newest version of this package **v.0.2.5** on npm. Your issue has been attended to. Please, letus know if you have anything more you would like us to look into.

Cheers

**Comment by stitchng** [comment]
Closing this issue out due to non-activity
