### ISSUE TITLE
Initialize Transaction Metadata Data Type is String

### ISSUE THREAD

**Issue by seunafara** [stitchng/paystack#18]
Going through the Paystack metadata documentation here, https://paystack.com/docs/payments/metadata/
Metadata is of type object. Why is this different in this package? When I checked metadata is of type string.

Is there something I am missing? Kindly help.

**Comment by isocroft** [comment]
Nothing is missing @seunafara . Please refer to the [API docs section for Transactions](https://paystack.com/docs/api/#transaction)

There are no noticeable discrepancies between the [Official Paystack API Reference](https://paystack.com/docs/api) and this package. I believe you are meant to stringify the `metadata` **object**.

See below:
  
![image](https://user-images.githubusercontent.com/5495952/107563307-31aa7380-6be1-11eb-820d-1cec6d26d039.png);

**Comment by seunafara** [comment]
Oh, I'll check this out and test. Thanks

**Comment by seunafara** [comment]
![image](https://user-images.githubusercontent.com/28274433/108077540-ea066a80-706c-11eb-8caa-0c9594398b55.png)

I just tried it tho. Does the error show in this image?

https://paystack.com/docs/payments/metadata/

**Comment by isocroft** [comment]
@seunafara like I said you are meant to stringify it using `JSON.stringify()` Web API. Like so:

```javascript
paystack.initializeTransaction({
   amount: business.claim_price,
   email: req.user.email,
   metadata: JSON.stringify({
      cart_id: 398,
      custom_fields: [
         { 
              display_name: "Invoice ID", 
              variable_name: "Invoice ID", 
              value: 209
         },
         { 
              display_name: "Cart Items", 
              variable_name: "cart_items", 
              value: "3 bananas, 12 mangoes"
         }
      ]
   }),
   callback_url: `${theAppUrl}/pay/process-payement`
});
```

**Comment by isocroft** [comment]
I will close this issue out now because there is really no issue here. 

Thanks for using `paystack-node` 😄 . Be sure that the package will continue to be maintained and upgraded 👍
