### ISSUE TITLE
unable to change popup button text Paystack with inline js 

### ISSUE THREAD

**Issue by Handavipul** [stitchng/paystack#24]
var paystk = new paystackpop();

paystk.newtransaction({
key : "new_key",
Email: "cc@gmail.com",
amount : 40,
currency : "ZAR" ,
style : {
text : "Hey"
}
})
I am unable to change the button text of the popup from "pay" to "hey"

**Comment by isocroft** [comment]
@Handavipul such a functionality does not exist for this package nor on paystack
